################################################################################
########################### Variables to change ################################

##### Choose the syntax extension you want between camlp4 (deprecated since
##### js_of_ocaml >= 2.7) and ppx (available for js_of_ocaml >= 2.7)
##### Default is ppx if SYNTAX_EXTENSION is set to different values than ppx or
##### camlp4
SYNTAX_EXTENSION	=	ppx

DEBUG				=	True

##### Directory where ml files are
ML_DIRECTORY		=	ml
##### ml files to compile into js. All files will be compiled at the same time.
##### Don't forget to add $(ML_DIR) before the filename.
ML_FILES 			=	$(ML_DIRECTORY)/test.ml

##### Directory where the output js file must be put in
ML_JS_DIRECTORY		=	js

##### The output js filename
ML_JS_OUTPUT_FILE	=	test.js

##### If you want to compile with some packages, add in this variable with
##### -package prefix.
CUSTOM_PACKAGE		=	-package ocaml-materializecss

##### If you want to compile with some syntax, add in this variable with
##### -syntax prefix.
CUSTOM_SYNTAX		=
################################################################################
